version: '3.8'

services:
  postgres:
    image: postgres:17.5-alpine
    container_name: ato-postgres
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql # Simplified for local testing

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ato-app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data: