version: '3.8'

services:
  postgres:
    ports:
      - "5432:5432"

  app:
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      # --- Development DB Connection ---
      DB_HOST: postgres # Connect to the service named 'postgres'
      DB_USER: devuser
      DB_PASSWORD: devpassword
      DB_NAME: devdb
      DB_PORT: 5432